.\" -*-Nroff-*-
.\"
.TH BBS 1 "15 Feb 2026" "2.3.10-Stilgar" "Unix User's Manual"
.SH NAME
bbs \- Connect to the ISCA BBS or a similar BBS.
.SH SYNOPSIS
.B bbs
[
\fIhost\fR
[
\fIport\fR
]
]
.SH DESCRIPTION
.B "bbs "
makes a connection to a D.O.C. style BBS
\fIhost\fR
on port
\fIport\fR.
If no
\fIport\fR
is specified, the default is 23, and if no
\fIhost\fR
is specified, the default is bbs.iscabbs.com (the ISCA BBS).
.sp
.B "bbs "
implements just enough of the
.B telnet
protocol to also be able to speak to standard telnet daemons, though for
normal usage you should probably use telnet instead.
.sp
This man page documents only the basics of IO ERROR's BBS Client; for
more specific usage information, please visit
.BR https://iscabbs.rocks/
.sp
This client targets macOS first. Other Unix-like systems receive
least-effort support and may still build and run in generic Unix mode.
.sp
When you log in for the first time, the client will remember your username,
and the next time you log in, you will not have to type it; you will only
need to type your password.
.sp
If you change your handle, the client will need to know your new handle.
Just press ENTER at the Password prompt, and type in your new handle. The
client will then remember your new handle.

.SH CONFIGURATION
To configure your client, you will enter the client configuration menu.
To do this, press \fBC\fRonfig then \fBC\fRlient from any BBS forum
prompt.

.SH HOT KEYS
Hot keys perform special functions in the client and also allow you to
activate your macros if you have defined any. To set up your hot keys,
use the \fBH\fRotkeys menu in the client configuration menu.
.TP
.B Command Key
Press this key to activate any of your macros or special functions below.
The default command key is Esc (you may also use Alt). If you have
upgraded from an older client, your command key may be set to Ctrl-B.
.TP
.B Quit Key
You can forcibly quit the client by pressing the command key then the
quit key, even if the BBS is not responding to your input. The default
quit key is Ctrl-D. If you have upgraded from an older client, your
quit key may be set to Ctrl-F.
.TP
.B Suspend Key
You can suspend the client and return to your Unix shell by pressing the
command key followed by the suspend key. To return to the
client when suspended, type "fg". The default suspend key is Ctrl-Z.
.TP
.B New Shell Key
You can start a subshell by pressing the command key followed by the new
shell key. To return to the
client from your subshell, type "exit". The default new shell key is !.
The shell command is taken from the SHELL environment variable and may
include optional arguments such as "fish -l", but it must still resolve
to an executable command line rather than shell syntax like pipes or
redirection.
.TP
.B Browser Key
You can open the current or most recently highlighted URL by pressing
the command key followed by the browser key. The default browser key is B.
.TP
.B Capture Key
You can start or stop capturing BBS output to a file by pressing the
command key followed by the capture key. The default capture key is C.
.TP
.B Away Key
You can mark yourself away by pressing the command key followed by the
away key. The default away key is A.

.SH EDITOR
If you use the built-in editor, the client uses its own line editor. You
can also configure an external editor in the client settings. The editor
value may include optional arguments such as "vim -f" or "code --wait",
and paths with spaces may be quoted. It must still resolve to an
executable command line rather than shell syntax.

.SH FILES
.TP
.I ~/.bbsrc
Client configuration file.
.TP
.I ~/.bbsfriends
Friend list.

.SH SEE ALSO
.BR telnet (1)

.SH AUTHOR
Originally by Michael Hampton (IO ERROR), with later work by other ISCA
contributors and this fork.
